In [262]:
import numpy as np

# 1. Вкладчик положил 50000 условных единиц на три разных счета в три разных банка. По первому счету выплаты составят 5% годовых, по второму – 7% годовых и по третьему 6% годовых. Известно, что через год вкладчик получил по процентам сумму в 2250 у.е. с первого и второго банка и сумму в 1400 у.е. с первого и третьего банка. Сколько условных единиц он положил на каждый счет изначально?
bank_1 + bank_2 + bank_3 = 50000                                                                                   
0.05 + 0.07 + 0 = 2250                                                                                             
0.05 + 0 + 0.06 = 1400

In [263]:
a = np.matrix("1,1,1;0.05,0.07,0;0.05,0,0.06")
b = np.matrix("50000;2250;1400")
a_inv = np.linalg.inv(a)
x = a_inv.dot(b)
print(x)

[[10000.]
 [25000.]
 [15000.]]


In [264]:
a = np.matrix("1,1,1;0.05,0.07,0;0.05,0,0.06")
b = np.matrix("50000;2250;1400")
a_det = round(np.linalg.det(a))
x = np.linalg.solve(a, b)
print(x)

[[10000.]
 [25000.]
 [15000.]]


# We cant use method Cramer because of determinant = Zero

In [265]:
# a = np.matrix("1,1,1;0.05,0.07,0;0.05,0,0.06")
# b = np.matrix("50000;2250;1400")
# a_det = round(np.linalg.det(a))
# a_1 = np.matrix(a)
# a_1[:, 0] = b
# a_2 = np.matrix(a)
# a_2[:, 1] = b
# a_3 = np.matrix(a)
# a_3[:, 2] = b
# x = [
#     round(np.linalg.det(a_1)) / a_det,
#     round(np.linalg.det(a_2)) / a_det,
#     round(np.linalg.det(a_3)) / a_det,
# ]
# print(x)

# 2. На складе хранятся мобильные телефоны iPhone 6, iPhone 11, iPhone 12 моделей. Всего 1328 экземпляра. Моделей iPhone 6 на 120 меньше, чем моделей iPhone 11, и на 100 больше, чем моделей iPhone 12. Сколько моделей каждого вида на складе?
iPhone_6 + iPhone_11 + iPhone_12 = 1328                                                                             
iPhone_6 - iPhone_11 + iPhone_12 = 120                                                                             
iPhone_6 + iPhone_11 - iPhone_12 = 100                                                                             

In [266]:
a = np.matrix("1,1,1;1,-1,0;1,0,-1")
b = np.matrix("1328;-120;100")
a_inv = np.linalg.inv(a)
x = a_inv.dot(b)
print(x)

[[436.]
 [556.]
 [336.]]


In [267]:
a = np.matrix("1,1,1;1,-1,0;1,0,-1")
b = np.matrix("1328;-120;100")
a_det = round(np.linalg.det(a))
x = np.linalg.solve(a, b)
print(x)

[[436.]
 [556.]
 [336.]]


In [268]:
a = np.matrix("1,1,1;1,-1,0;1,0,-1")
b = np.matrix("1328;-120;100")
a_det = round(np.linalg.det(a))
a_1 = np.matrix(a)
a_1[:, 0] = b
a_2 = np.matrix(a)
a_2[:, 1] = b
a_3 = np.matrix(a)
a_3[:, 2] = b
x = [
    round(np.linalg.det(a_1)) / a_det,
    round(np.linalg.det(a_2)) / a_det,
    round(np.linalg.det(a_3)) / a_det,
]
print(x)

[436.0, 556.0, 336.0]


# 3. Составьте каноническое уравнение эллипсоида, проходящего через три точки A,B,C. 
A(sqrt(3); 0; sqrt(3) B(sqrt(6); 0.5; 0) C(1; 1/sqrt(3); 1) 
Каноническое уравнение эллипсоида в прямоугольной декартовой системе координат имеет вид:
x*2/a*2 + y*2/b*2 + z*2/c*2                                                                                         
3/a*2 + 3/c*2 = 1                                                                                                   
6/a*2 + 1/4/b*2 = 1                                                                                                 
1/a*2 + 1/3/b*2 + 1/c*2 = 1                                                                                         

q = 1/a*2                                                                                                           
w = 1/b*2                                                                                                           
e = 1/c*2                                                                                                           

3q + 3e = 1                                                                                                         
6q + 1/4w = 1                                                                                                       
q + 1/3w + e = 1                                                                                                   

In [269]:
a = np.array([[3, 0, 3], [6, 0.25, 0], [1, 0.33, 1]])
b = np.array([1, 1, 1])
a_det = round(np.linalg.det(a))
x = np.linalg.solve(a, b)
print(x)

[0.08249158 2.02020202 0.25084175]


In [270]:
a = (1/np.sqrt(x[0]), -1/np.sqrt(x[0]))
b = (1/np.sqrt(x[1]), -1/np.sqrt(x[1]))
c = (1/np.sqrt(x[2]), -1/np.sqrt(x[2]))

print(a)
print(b)
print(c)

(3.4817307448439827, -3.4817307448439827)
(0.7035623639735145, -0.7035623639735145)
(1.9966414753801076, -1.9966414753801076)


# 4. Составьте уравнение параболы проходящей через заданные три точки (1,12), (3,54), (-1,2). Необходимо найти коэффициенты уравнения a,b,c.
y = a*x*2 + b*x + c                                                                                                 
12 = x1 + x2 + x3                                                                                                   
54 = 9x1 + 3x2 + x3                                                                                                 
2 = x1 - x2 + x3                                                                                                   

In [271]:
a = np.matrix("1,1,1;9,3,1;1,-1,1")
b = np.matrix("12;54;2")
a_det = round(np.linalg.det(a))
x = np.linalg.solve(a, b)
print(x)

[[4.]
 [5.]
 [3.]]


# 5. Составьте функцию get_polynom, которая по набору точек вида (x1,y1),(x2,y2),…,(xn+1,yn+1) будет находить коэффициенты многочлена c.
 

y = a * x * 2 + b * x + c

In [272]:
def get_polynom(coords):
    b = np.array([])
    list_of_x_items = []
    for x, y in coords:
        array = [x ** i for i in reversed(range(len(coords)))]
        list_of_x_items.append(array)
        b = np.append(b, y)
    a = np.array(list_of_x_items)
    return np.round(np.linalg.solve(a, b))

In [273]:
print(get_polynom([(1, 10), (2, 0), (3, 0), (4, 16), (5, 54), (6, 120)]))

[ -0.   0.   1.  -1. -14.  24.]
